version: '3.4'

services:
  app:
    image: go-htmx-chat
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    env_file:
      - ./.env
    ports:
      - 5000:5000
    volumes:
      - .:/app
